
import type { Metadata } from "next";
import { Nunito_Sans, Geist_Mono, Nunito, } from "next/font/google";
import HeaderBar, { HeaderNavLink } from "@/app/ui/HeaderBar";
import Banner from "@/app/ui/Banner";
import FooterBar from "@/app/ui/FooterBar";
import "@/app/globals.css";
import "7.css"

const nunitoSans = Nunito({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CS Club @ Harper | Home",
  description: "Generated by create next app",
};


export default function AdminRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${nunitoSans.className}`}>
      <body
        className="antialiased text-foreground dark:text-foregroundDark m-0 min-h-screen">
        <header>
        </header>
        <main className="bg-cyan-600 min-h-screen!  min-w-full  justify-center items-center ">
          <div className="mx-[5px] sm:mx-[25vw] py-[50px]">
            {children}
          </div>
        </main>
        <footer>
          <FooterBar />
        </footer>
      </body>
    </html >
  );
}
