import type { Metadata } from "next";
import { Nunito_Sans, Geist_Mono, } from "next/font/google";
import HeaderBar from "./ui/HeaderBar";
import Banner from "./ui/Banner";
import FooterBar from "./ui/FooterBar";
import "./globals.css";

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${nunitoSans.className}`}>
      <body
        className="antialiased text-foreground! m-0! min-h-screen">
        <header>
          <Banner />
          <HeaderBar />
        </header>
        <main className="aero-bg-gray min-h-screen!  min-w-full  justify-center items-center ">
          <div className="mx-[5px] sm:mx-[25vw] py-[50px]">
            {children}
          </div>
        </main>
        <footer>
          <FooterBar />
        </footer>
      </body>
    </html >
  );
}
