import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderBar from "./ui/HeaderBar";
import Banner from "./ui/Banner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased
        m-0! min-h-screen! flex flex-col             `}
      >
        <header>
          <Banner />
          <HeaderBar />
        </header>
        <main className="aero-bg-gray min-h-full!  min-w-full  justify-center items-center  ">
          <div className="mx-[5px] sm:mx-[25vw] my-[50px]">
            {children}
          </div>
        </main>
      </body>
    </html >
  );
}
